services:
  - type: web
    name: n8n
    env: docker
    plan: free
    docker:
      dockerfilePath: Dockerfile
    port: 5678
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_HOST
        value: localhost
      - key: N8N_PROTOCOL
        value: http
      - key: GENERIC_TIMEZONE
        value: America/Havana
      - key: N8N_ENCRYPTION_KEY
        value: {ty:2,N8z3y4~~m]|<:BS7f
      - key: NODE_OPTIONS
        value: "--max_old_space_size=460"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_LOG_LEVEL
        value: "error"
